language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t clavender/docker-tutorial -f Dockerfile.dev .

script:
  - docker run -e CI=true clavender/docker-tutorial npm run test -- --coverage

  deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-tutorial"
    env: "DockerTutorial-env-2"
    bucket_name: "elasticbeanstalk-us-east-1-663568631822"
    bucket_path: "docker-tutorial"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY